name: AOSC Artifacts

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  IMAGE_NAME: aosc
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker file
        id: docker_gen
        run: |
          sudo apt update && sudo apt install -y squashfs-tools-ng
          cd ${{ github.workspace }}/AOSC
          bash gen_dockerfile.sh     

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push AOSC Images
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/AOSC
          platforms: linux/loong64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.docker_gen.outputs.IMG_VER }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:buildkit
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
